theme: jekyll-theme-minimal
title: Keyple API Documentation
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: "*/[0-9]*"
    values:
      sitemap: false
exclude:
  - "keyple-*/"
include:
  - "_*.html"
