name: Update Submodules and Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-submodules]
  push:
    branches:
      - gh-pages-source

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    env:
      GIT_USER_NAME: Eclipse Keyple Bot
      GIT_USER_EMAIL: ${{ github.repository }}-bot@eclipse.org
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages-source
          submodules: recursive
          fetch-depth: 0

      - name: Set Git user identity
        run: |
          git config --global user.name "${GIT_USER_NAME}"
          git config --global user.email "${GIT_USER_EMAIL}"

      - name: Make script executable
        run: chmod +x .github/scripts/update_and_publish.sh

      - name: Execute update and publish script
        run: .github/scripts/update_and_publish.sh
        env:
          GIT_USER_NAME: ${{ github.env.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ github.env.GIT_USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
